cat_breeds = [
    {"name": "Абиссинская", "original_name": "Abyssinian", "tags": ["short-haired", "короткошёрстная", "active", "активная", "slim", "стройная", "ticked coat", "тикированный окрас", "medium-sized", "среднего размера", "natural", "природная"]},
    {"name": "Эгейская", "original_name": "Aegean", "tags": ["semi-long-haired", "полудлинношёрстная", "natural", "природная", "moderate", "умеренная", "multi-color", "многоцветная"]},
    {"name": "Американский бобтейл", "original_name": "American Bobtail", "tags": ["short-tailed", "короткохвостая", "muscular", "мускулистая", "semi-long-haired", "полудлинношёрстная", "playful", "игривая"]},
    {"name": "Американский кёрл", "original_name": "American Curl", "tags": ["curled ears", "загнутые уши", "semi-foreign", "полуиностранного типа", "medium-sized", "среднего размера", "gentle", "нежная"]},
    {"name": "Американский рингтейл", "original_name": "American Ringtail", "tags": ["ring-tailed", "кольцехвостая", "experimental", "экспериментальная", "active", "активная", "semi-long-haired", "полудлинношёрстная"]},
    {"name": "Американская короткошёрстная", "original_name": "American Shorthair", "tags": ["short-haired", "короткошёрстная", "robust", "крепкая", "cobby", "коренастая", "all colors", "все окрасы"]},
    {"name": "Американская жесткошёрстная", "original_name": "American Wirehair", "tags": ["rex", "рексовый", "short-haired", "короткошёрстная", "muscular", "мускулистая", "unusual coat", "необычная шерсть"]},
    {"name": "Афродита гигантская", "original_name": "Aphrodite Giant", "tags": ["giant", "гигантская", "natural", "природная", "muscular", "мускулистая", "all coat lengths", "любая длина шерсти"]},
    {"name": "Аравийский мау", "original_name": "Arabian Mau", "tags": ["short-haired", "короткошёрстная", "desert", "пустынная", "natural", "природная", "moderate", "умеренная"]},
    {"name": "Азиатская", "original_name": "Asian", "tags": ["short-haired", "короткошёрстная", "moderate", "умеренная", "crossbreed", "межпородная", "no white", "без белого"]},
    {"name": "Азиатская полудлинношёрстная", "original_name": "Asian Semi-longhair", "tags": ["semi-long-haired", "полудлинношёрстная", "moderate", "умеренная", "crossbreed", "межпородная", "gentle", "нежная"]},
    {"name": "Австралийский мист", "original_name": "Australian Mist", "tags": ["short-haired", "короткошёрстная", "spotted", "пятнистая", "marbled", "мраморная", "friendly", "дружелюбная"]},
    {"name": "Балинезийская", "original_name": "Balinese", "tags": ["long-haired", "длинношёрстная", "colorpoint", "колор-пойнт", "semi-foreign", "полуиностранного типа", "vocal", "разговорчивая"]},
    {"name": "Бамбино", "original_name": "Bambino", "tags": ["dwarf", "карликовая", "hairless", "бесшёрстная", "short legs", "короткие лапы", "experimental", "экспериментальная"]},
    {"name": "Бенгальская", "original_name": "Bengal", "tags": ["short-haired", "короткошёрстная", "spotted", "пятнистая", "wild look", "дикий вид", "energetic", "энергичная"]},
    {"name": "Бирманская", "original_name": "Birman", "tags": ["semi-long-haired", "полудлинношёрстная", "colorpoint", "колор-пойнт", "white paws", "белые лапы", "gentle", "нежная"]},
    {"name": "Бомбейская", "original_name": "Bombay", "tags": ["short-haired", "короткошёрстная", "solid black", "сплошной чёрный", "muscular", "мускулистая", "friendly", "дружелюбная"]},
    {"name": "Бразильская короткошёрстная", "original_name": "Brazilian Shorthair", "tags": ["short-haired", "короткошёрстная", "natural", "природная", "all colors", "все окрасы", "moderate", "умеренная"]},
    {"name": "Британская длинношёрстная", "original_name": "British Longhair", "tags": ["long-haired", "длинношёрстная", "cobby", "коренастая", "calm", "спокойная", "fluffy", "пушистая"]},
    {"name": "Британская короткошёрстная", "original_name": "British Shorthair", "tags": ["short-haired", "короткошёрстная", "cobby", "коренастая", "calm", "спокойная", "dense coat", "плотная шерсть"]},
    {"name": "Бурманская", "original_name": "Burmese", "tags": ["short-haired", "короткошёрстная", "muscular", "мускулистая", "golden eyes", "золотые глаза", "friendly", "дружелюбная"]},
    {"name": "Бурмилла", "original_name": "Burmilla", "tags": ["short-haired", "короткошёрстная", "silver", "серебристая", "semi-cobby", "полукоренастая", "gentle", "нежная"]},
    {"name": "Калифорнийская сияющая", "original_name": "California Spangled", "tags": ["short-haired", "короткошёрстная", "spotted", "пятнистая", "wild look", "дикий вид", "active", "активная"]},
    {"name": "Шантильи-Тиффани", "original_name": "Chantilly-Tiffany", "tags": ["long-haired", "длинношёрстная", "chocolate", "шоколадная", "gentle", "нежная", "rare", "редкая"]},
    {"name": "Шартрез", "original_name": "Chartreux", "tags": ["short-haired", "короткошёрстная", "blue", "голубая", "smiling", "улыбчивая", "calm", "спокойная"]},
    {"name": "Чаузи", "original_name": "Chausie", "tags": ["short-haired", "короткошёрстная", "wild hybrid", "дикий гибрид", "tall", "высокая", "active", "активная"]},
    {"name": "Колорпойнт короткошёрстная", "original_name": "Colorpoint Shorthair", "tags": ["short-haired", "короткошёрстная", "colorpoint", "колор-пойнт", "vocal", "разговорчивая", "oriental", "ориентальная"]},
    {"name": "Корниш-рекс", "original_name": "Cornish Rex", "tags": ["rex", "рексовый", "curly", "кудрявая", "large ears", "большие уши", "active", "активная"]},
    {"name": "Кимрик", "original_name": "Cymric", "tags": ["long-haired", "длинношёрстная", "tailless", "бесхвостая", "cobby", "коренастая", "gentle", "нежная"]},
    {"name": "Кипрская", "original_name": "Cyprus", "tags": ["natural", "природная", "all coat lengths", "любая длина шерсти", "muscular", "мускулистая", "active", "активная"]},
    {"name": "Девон-рекс", "original_name": "Devon Rex", "tags": ["rex", "рексовый", "large ears", "большие уши", "elfin look", "эльфийский вид", "playful", "игривая"]},
    {"name": "Донской сфинкс", "original_name": "Donskoy", "tags": ["hairless", "бесшёрстная", "wrinkled", "морщинистая", "medium-sized", "среднего размера", "friendly", "дружелюбная"]},
    {"name": "Дракон Ли", "original_name": "Dragon Li", "tags": ["short-haired", "короткошёрстная", "ticked", "тикированная", "natural", "природная", "active", "активная"]},
    {"name": "Двельф", "original_name": "Dwelf", "tags": ["dwarf", "карликовая", "hairless", "бесшёрстная", "curled ears", "загнутые уши", "experimental", "экспериментальная"]},
    {"name": "Египетская мау", "original_name": "Egyptian Mau", "tags": ["short-haired", "короткошёрстная", "spotted", "пятнистая", "muscular", "мускулистая", "active", "активная"]},
    {"name": "Европейская короткошёрстная", "original_name": "European Shorthair", "tags": ["short-haired", "короткошёрстная", "natural", "природная", "all colors", "все окрасы", "moderate", "умеренная"]},
    {"name": "Экзотическая короткошёрстная", "original_name": "Exotic Shorthair", "tags": ["short-haired", "короткошёрстная", "flat-faced", "плоскомордая", "calm", "спокойная", "cobby", "коренастая"]},
    {"name": "Фолдекс", "original_name": "Foldex", "tags": ["folded ears", "вислоухая", "short-haired", "короткошёрстная", "cobby", "коренастая", "rare", "редкая"]},
    {"name": "Немецкий рекс", "original_name": "German Rex", "tags": ["rex", "рексовый", "curly", "кудрявая", "medium-sized", "среднего размера", "active", "активная"]},
    {"name": "Гавана браун", "original_name": "Havana Brown", "tags": ["short-haired", "короткошёрстная", "brown", "коричневая", "green eyes", "зелёные глаза", "semi-foreign", "полуиностранного типа"]},
    {"name": "Хайлендер", "original_name": "Highlander", "tags": ["curled ears", "загнутые уши", "wild look", "дикий вид", "muscular", "мускулистая", "large", "крупная"]},
    {"name": "Гималайская", "original_name": "Himalayan", "tags": ["long-haired", "длинношёрстная", "colorpoint", "колор-пойнт", "flat-faced", "плоскомордая", "calm", "спокойная"]},
    {"name": "Японский бобтейл", "original_name": "Japanese Bobtail", "tags": ["short-tailed", "короткохвостая", "natural", "природная", "active", "активная", "vocal", "разговорчивая"]},
    {"name": "Яванская", "original_name": "Javanese", "tags": ["long-haired", "длинношёрстная", "colorpoint", "колор-пойнт", "vocal", "разговорчивая", "oriental", "ориентальная"]},
    {"name": "Канаани", "original_name": "Kanaani", "tags": ["short-haired", "короткошёрстная", "wild hybrid", "дикий гибрид", "spotted", "пятнистая", "active", "активная"]},
    {"name": "Карельский бобтейл", "original_name": "Karelian Bobtail", "tags": ["short-tailed", "короткохвостая", "natural", "природная", "semi-long-haired", "полудлинношёрстная", "active", "активная"]},
    {"name": "Као-мани", "original_name": "Khao Manee", "tags": ["short-haired", "короткошёрстная", "white", "белая", "odd-eyed", "разноглазая", "rare", "редкая"]},
    {"name": "Кинкалоу", "original_name": "Kinkalow", "tags": ["dwarf", "карликовая", "curled ears", "загнутые уши", "short-legged", "коротколапая", "playful", "игривая"]},
    {"name": "Корат", "original_name": "Korat", "tags": ["short-haired", "короткошёрстная", "blue", "голубая", "heart-shaped face", "сердцевидная морда", "gentle", "нежная"]},
    {"name": "Корейский бобтейл", "original_name": "Korean Bobtail", "tags": ["short-tailed", "короткохвостая", "natural", "природная", "semi-long-haired", "полудлинношёрстная", "active", "активная"]},
    {"name": "Корн-джа", "original_name": "Korn Ja", "tags": ["short-haired", "короткошёрстная", "black", "чёрная", "natural", "природная", "rare", "редкая"]},
    {"name": "Курильский бобтейл", "original_name": "Kurilian Bobtail", "tags": ["short-tailed", "короткохвостая", "natural", "природная", "muscular", "мускулистая", "active", "активная"]},
    {"name": "Ламбкин", "original_name": "Lambkin", "tags": ["dwarf", "карликовая", "rex", "рексовый", "curly", "кудрявая", "playful", "игривая"]},
    {"name": "Лаперм", "original_name": "LaPerm", "tags": ["rex", "рексовый", "curly", "кудрявая", "all coat lengths", "любая длина шерсти", "affectionate", "ласковая"]},
    {"name": "Ликой", "original_name": "Lykoi", "tags": ["werewolf", "оборотень", "partially hairless", "частично бесшёрстная", "yellow eyes", "жёлтые глаза", "active", "активная"]},
    {"name": "Мейн-кун", "original_name": "Maine Coon", "tags": ["giant", "гигантская", "long-haired", "длинношёрстная", "tufted ears", "кисточки на ушах", "friendly", "дружелюбная"]},
    {"name": "Мэнкс", "original_name": "Manx", "tags": ["tailless", "бесхвостая", "cobby", "коренастая", "round", "круглая", "playful", "игривая"]},
    {"name": "Меконгский бобтейл", "original_name": "Mekong Bobtail", "tags": ["short-tailed", "короткохвостая", "colorpoint", "колор-пойнт", "muscular", "мускулистая", "active", "активная"]},
    {"name": "Минскин", "original_name": "Minskin", "tags": ["dwarf", "карликовая", "short-legged", "коротколапая", "hairless patches", "участки без шерсти", "playful", "игривая"]},
    {"name": "Минуэт", "original_name": "Minuet", "tags": ["dwarf", "карликовая", "short-legged", "коротколапая", "flat-faced", "плоскомордая", "calm", "спокойная"]},
    {"name": "Манчкин", "original_name": "Munchkin", "tags": ["dwarf", "карликовая", "short-legged", "коротколапая", "all coat lengths", "любая длина шерсти", "playful", "игривая"]},
    {"name": "Небелунг", "original_name": "Nebelung", "tags": ["long-haired", "длинношёрстная", "blue", "голубая", "green eyes", "зелёные глаза", "shy", "застенчивая"]},
    {"name": "Невская маскарадная", "original_name": "Neva Masquerade", "tags": ["long-haired", "длинношёрстная", "colorpoint", "колор-пойнт", "hypoallergenic", "гипоаллергенная", "large", "крупная"]},
    {"name": "Норвежская лесная", "original_name": "Norwegian Forest Cat", "tags": ["giant", "гигантская", "long-haired", "длинношёрстная", "tufted ears", "кисточки на ушах", "natural", "природная"]},
    {"name": "Оцикет", "original_name": "Ocicat", "tags": ["short-haired", "короткошёрстная", "spotted", "пятнистая", "muscular", "мускулистая", "active", "активная"]},
    {"name": "Охос азулес", "original_name": "Ojos Azules", "tags": ["short-haired", "короткошёрстная", "blue eyes", "голубые глаза", "rare", "редкая", "all colors", "все окрасы"]},
    {"name": "Ориентальная биколор", "original_name": "Oriental Bicolor", "tags": ["short-haired", "короткошёрстная", "bicolor", "двухцветная", "slim", "стройная", "vocal", "разговорчивая"]},
    {"name": "Ориентальная длинношёрстная", "original_name": "Oriental Longhair", "tags": ["long-haired", "длинношёрстная", "slim", "стройная", "vocal", "разговорчивая", "oriental", "ориентальная"]},
    {"name": "Ориентальная короткошёрстная", "original_name": "Oriental Shorthair", "tags": ["short-haired", "короткошёрстная", "slim", "стройная", "large ears", "большие уши", "vocal", "разговорчивая"]},
    {"name": "Персидская (современная)", "original_name": "Persian (modern)", "tags": ["long-haired", "длинношёрстная", "flat-faced", "плоскомордая", "calm", "спокойная", "high-maintenance", "требовательная в уходе"]},
    {"name": "Персидская (традиционная)", "original_name": "Persian (traditional)", "tags": ["long-haired", "длинношёрстная", "doll-face", "кукольная морда", "calm", "спокойная", "healthy", "здоровая"]},
    {"name": "Петерболд", "original_name": "Peterbald", "tags": ["hairless", "бесшёрстная", "slim", "стройная", "large ears", "большие уши", "elegant", "элегантная"]},
    {"name": "Пикси-боб", "original_name": "Pixie-bob", "tags": ["short-tailed", "короткохвостая", "muscular", "мускулистая", "spotted", "пятнистая", "wild look", "дикий вид"]},
    {"name": "Рагамаффин", "original_name": "Ragamuffin", "tags": ["long-haired", "длинношёрстная", "gentle", "нежная", "large", "крупная", "all colors", "все окрасы"]},
    {"name": "Рэгдолл", "original_name": "Ragdoll", "tags": ["long-haired", "длинношёрстная", "docile", "покладистая", "colorpoint", "колор-пойнт", "gentle", "нежная"]},
    {"name": "Раас", "original_name": "Raas", "tags": ["short-haired", "короткошёрстная", "blue", "голубая", "cinnamon", "коричная", "rare", "редкая"]},
    {"name": "Русская голубая", "original_name": "Russian Blue", "tags": ["short-haired", "короткошёрстная", "blue", "голубая", "green eyes", "зелёные глаза", "elegant", "элегантная"]},
    {"name": "Русская белая/чёрная/табби", "original_name": "Russian White/Black/Tabby", "tags": ["short-haired", "короткошёрстная", "white", "белая", "black", "чёрная", "tabby", "табби"]},
    {"name": "Сам Савет", "original_name": "Sam Sawet", "tags": ["short-haired", "короткошёрстная", "muscular", "мускулистая", "natural", "природная", "active", "активная"]},
    {"name": "Саванна", "original_name": "Savannah", "tags": ["short-haired", "короткошёрстная", "tall", "высокая", "spotted", "пятнистая", "wild hybrid", "дикий гибрид"]},
    {"name": "Шотландская вислоухая", "original_name": "Scottish Fold", "tags": ["folded ears", "вислоухая", "round face", "круглая морда", "calm", "спокойная", "all coat lengths", "любая длина шерсти"]},
    {"name": "Селкирк-рекс", "original_name": "Selkirk Rex", "tags": ["rex", "рексовый", "curly", "кудрявая", "cobby", "коренастая", "gentle", "нежная"]},
    {"name": "Серенгети", "original_name": "Serengeti", "tags": ["short-haired", "короткошёрстная", "spotted", "пятнистая", "tall", "высокая", "wild look", "дикий вид"]},
    {"name": "Сиамская (современная)", "original_name": "Siamese (modern)", "tags": ["short-haired", "короткошёрстная", "colorpoint", "колор-пойнт", "vocal", "разговорчивая", "oriental", "ориентальная"]},
    {"name": "Сибирская", "original_name": "Siberian", "tags": ["long-haired", "длинношёрстная", "hypoallergenic", "гипоаллергенная", "large", "крупная", "natural", "природная"]},
    {"name": "Сингапурская", "original_name": "Singapura", "tags": ["small", "маленькая", "short-haired", "короткошёрстная", "ticked", "тикированная", "active", "активная"]},
    {"name": "Сноу-шу", "original_name": "Snowshoe", "tags": ["short-haired", "короткошёрстная", "colorpoint", "колор-пойнт", "white paws", "белые лапы", "gentle", "нежная"]},
    {"name": "Сококе", "original_name": "Sokoke", "tags": ["short-haired", "короткошёрстная", "marbled", "мраморная", "active", "активная", "rare", "редкая"]},
    {"name": "Сомалийская", "original_name": "Somali", "tags": ["long-haired", "длинношёрстная", "ticked", "тикированная", "active", "активная", "fluffy", "пушистая"]},
    {"name": "Сфинкс", "original_name": "Sphynx", "tags": ["hairless", "бесшёрстная", "wrinkled", "морщинистая", "large ears", "большие уши", "active", "активная"]},
    {"name": "Суфалак", "original_name": "Suphalak", "tags": ["short-haired", "короткошёрстная", "brown", "коричневая", "rare", "редкая", "natural", "природная"]},
    {"name": "Тайская", "original_name": "Thai", "tags": ["short-haired", "короткошёрстная", "colorpoint", "колор-пойнт", "moderate", "умеренная", "vocal", "разговорчивая"]},
    {"name": "Тайская лилак/блю-пойнт", "original_name": "Thai Lilac/Blue Point", "tags": ["short-haired", "короткошёрстная", "lilac", "лиловая", "blue point", "блю-пойнт", "rare", "редкая"]},
    {"name": "Тонкинская", "original_name": "Tonkinese", "tags": ["short-haired", "короткошёрстная", "mink pattern", "норковый окрас", "aqua eyes", "аквамариновые глаза", "playful", "игривая"]},
    {"name": "Тойбоб", "original_name": "Toybob", "tags": ["dwarf", "карликовая", "short-tailed", "короткохвостая", "tiny", "крошечная", "playful", "игривая"]},
    {"name": "Тойгер", "original_name": "Toyger", "tags": ["short-haired", "короткошёрстная", "striped", "полосатая", "muscular", "мускулистая", "wild look", "дикий вид"]},
    {"name": "Турецкая ангора", "original_name": "Turkish Angora", "tags": ["long-haired", "длинношёрстная", "white", "белая", "elegant", "элегантная", "active", "активная"]},
    {"name": "Турецкий ван", "original_name": "Turkish Van", "tags": ["semi-long-haired", "полудлинношёрстная", "van pattern", "ванский окрас", "active", "активная", "swimmer", "плавающая"]},
    {"name": "Турецкая ванкедиси", "original_name": "Turkish Vankedisi", "tags": ["long-haired", "длинношёрстная", "white", "белая", "active", "активная", "all-white", "полностью белая"]},
    {"name": "Украинский левкой", "original_name": "Ukrainian Levkoy", "tags": ["hairless", "бесшёрстная", "folded ears", "вислоухая", "experimental", "экспериментальная", "unusual", "необычная"]},
    {"name": "Йоркская шоколадная", "original_name": "York Chocolate", "tags": ["long-haired", "длинношёрстная", "chocolate", "шоколадная", "lilac", "лиловая", "gentle", "нежная"]}
]